import { filterVarsForPlatform, generateEnvFile } from './shared.js';

const MOLTBOT_REPO = 'https://github.com/user/MOtdbot-cloudfare.git';

export function generateSecretsScript(vars: Record<string, string>): string {
  const filtered = filterVarsForPlatform(vars, 'cloudflare');
  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by create-moltbot',
    '# Sets all Cloudflare Workers secrets via wrangler',
    '',
    'set -e',
    '',
    'echo "Setting Cloudflare Workers secrets..."',
    'SUCCESS=0',
    'FAILED=0',
    '',
  ];

  for (const [key, value] of Object.entries(filtered)) {
    lines.push(`echo "Setting ${key}..."`);
    lines.push(`echo "${value.replace(/"/g, '\\"')}" | wrangler secret put ${key} && SUCCESS=$((SUCCESS+1)) || FAILED=$((FAILED+1))`);
    lines.push('');
  }

  lines.push('echo ""');
  lines.push('echo "Done! $SUCCESS secrets set successfully, $FAILED failed."');

  return lines.join('\n') + '\n';
}

export function generateDevVars(vars: Record<string, string>): string {
  const filtered = filterVarsForPlatform(vars, 'cloudflare');
  return generateEnvFile(filtered, 'Cloudflare Workers local development variables (.dev.vars)');
}

export interface CloudflareDeploySteps {
  steps: string[];
  commands: string[];
}

export function getDeploySteps(outputDir: string): CloudflareDeploySteps {
  return {
    steps: [
      'Check wrangler authentication',
      'Clone Moltbot repository',
      'Install dependencies',
      'Set secrets',
      'Build and deploy',
    ],
    commands: [
      'wrangler whoami',
      `git clone ${MOLTBOT_REPO} "${outputDir}/moltbot"`,
      `cd "${outputDir}/moltbot" && npm ci`,
      `cd "${outputDir}/moltbot" && bash ../secrets.sh`,
      `cd "${outputDir}/moltbot" && npm run deploy`,
    ],
  };
}
