import Handlebars from 'handlebars';
import { filterVarsForPlatform, generateEnvFile } from './shared.js';

interface DockerConfig {
  vars: Record<string, string>;
  browserEnabled: boolean;
}

const COMPOSE_TEMPLATE = `# Generated by create-moltbot
# Run: docker compose up -d

services:
  moltbot:
    image: ghcr.io/jamese/moltbot:latest
    restart: unless-stopped
    volumes:
      - moltbot-config:/root/.openclaw
      - moltbot-workspace:/root/clawd
    env_file: .env
    ports:
      - "18789:18789"
    networks:
      - moltbot
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:18789/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

{{#if hasDomain}}
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      moltbot:
        condition: service_healthy
    networks:
      - moltbot
{{/if}}

{{#if browserEnabled}}
  chromium:
    image: browserless/chromium:latest
    restart: unless-stopped
    environment:
      - CONNECTION_TIMEOUT=600000
      - MAX_CONCURRENT_SESSIONS=2
    networks:
      - moltbot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/json/version"]
      interval: 30s
      timeout: 5s
      retries: 3
{{/if}}

volumes:
  moltbot-config:
  moltbot-workspace:
{{#if hasDomain}}
  caddy-data:
  caddy-config:
{{/if}}

networks:
  moltbot:
`;

const CADDYFILE_TEMPLATE = `# Generated by create-moltbot
{{#if acmeEmail}}
{
    email {{acmeEmail}}
}
{{/if}}

{{domain}} {
{{#if hasAuth}}
    basicauth /* {
        {{authUser}} {{authHash}}
    }
{{/if}}

    # Public endpoints (no auth required)
    @public {
        path /api/status
        path /telegram/webhook
        path /telegram-webhook
    }
    handle @public {
        reverse_proxy moltbot:18789
    }

    # Everything else
    reverse_proxy moltbot:18789

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        X-XSS-Protection "1; mode=block"
        Referrer-Policy strict-origin-when-cross-origin
    }
}
`;

export function generateDockerCompose(config: DockerConfig): string {
  const template = Handlebars.compile(COMPOSE_TEMPLATE);
  return template({
    hasDomain: !!config.vars['DOMAIN']?.trim(),
    browserEnabled: config.browserEnabled,
  });
}

export function generateCaddyfile(vars: Record<string, string>): string {
  const template = Handlebars.compile(CADDYFILE_TEMPLATE);
  return template({
    domain: vars['DOMAIN'] || 'localhost',
    acmeEmail: vars['ACME_EMAIL'] || '',
    hasAuth: !!(vars['AUTH_USER']?.trim() && vars['AUTH_PASSWORD']?.trim()),
    authUser: vars['AUTH_USER'] || '',
    authHash: vars['AUTH_PASSWORD'] || '', // In real deploy, should be bcrypt hash
  });
}

export function generateDockerEnv(vars: Record<string, string>): string {
  const filtered = filterVarsForPlatform(vars, 'docker');
  return generateEnvFile(filtered, 'Moltbot Docker deployment');
}

export interface DockerDeployFiles {
  'docker-compose.yml': string;
  '.env': string;
  Caddyfile?: string;
  '.gitignore': string;
}

export function generateAllDockerFiles(config: DockerConfig): DockerDeployFiles {
  const files: DockerDeployFiles = {
    'docker-compose.yml': generateDockerCompose(config),
    '.env': generateDockerEnv(config.vars),
    '.gitignore': '.env\n.secrets\n',
  };

  if (config.vars['DOMAIN']?.trim()) {
    files['Caddyfile'] = generateCaddyfile(config.vars);
  }

  return files;
}
