import crypto from 'node:crypto';

export function generateToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString('hex');
}

export function maskSecret(value: string): string {
  if (value.length <= 8) return '****';
  return value.slice(0, 4) + '****' + value.slice(-4);
}

export function generateEnvFile(
  vars: Record<string, string>,
  header?: string
): string {
  const lines: string[] = [];

  if (header) {
    lines.push(`# ${header}`);
    lines.push(`# Generated by create-moltbot on ${new Date().toISOString()}`);
    lines.push('# WARNING: This file contains secrets. Do not commit to version control.');
    lines.push('');
  }

  for (const [key, value] of Object.entries(vars)) {
    if (!value?.trim()) continue;
    // Quote values that contain spaces or special characters
    const needsQuotes = /[\s#"'\\$]/.test(value);
    lines.push(`${key}=${needsQuotes ? `"${value.replace(/"/g, '\\"')}"` : value}`);
  }

  return lines.join('\n') + '\n';
}

export function filterVarsForPlatform(
  vars: Record<string, string>,
  platform: 'cloudflare' | 'docker'
): Record<string, string> {
  // Remove platform-specific vars that don't apply
  const dockerOnly = ['AUTH_USER', 'AUTH_PASSWORD', 'DOMAIN', 'ACME_EMAIL'];
  const cloudflareOnly = [
    'CF_ACCESS_TEAM_DOMAIN', 'CF_ACCESS_AUD',
    'AI_GATEWAY_API_KEY', 'AI_GATEWAY_BASE_URL',
    'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY', 'CF_ACCOUNT_ID',
    'SANDBOX_SLEEP_AFTER',
  ];

  const exclude = platform === 'cloudflare' ? dockerOnly : cloudflareOnly;
  const filtered: Record<string, string> = {};

  for (const [key, value] of Object.entries(vars)) {
    if (!exclude.includes(key) && value?.trim()) {
      filtered[key] = value;
    }
  }

  return filtered;
}
